name: flutter_application_1
description: "اپ عاشقونه - چت، تقویم، پریود، لحظه‌ها"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ================= CORE =================
  provider: ^6.1.5
  shared_preferences: ^2.5.5

  # ================= LOCAL STORAGE =================
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ================= NETWORK =================
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  connectivity_plus: ^7.1.1

  # ================= MEDIA =================
  video_player: ^2.11.1
  image_picker: ^1.2.2
  file_picker: ^8.3.7

  # image compress (keep stable version)
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1

  # ================= CALENDAR =================
  shamsi_date: ^1.1.1
  persian_datetime_picker: ^3.2.0

  # ================= LOCATION =================
  geolocator: ^13.0.4

  # ================= UI =================
  lottie: ^3.3.3
  shimmer: ^3.0.0
  pinput: ^3.0.1

  # ================= DEVICE INFO =================
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1

  # ================= SHARE =================
  share_plus: ^10.1.4

  # ================= LOCALIZATION =================
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/lottie/female_avatar.json
    - assets/lottie/male_avatar.json

  fonts:
    - family: titr
      fonts:
        - asset: fonts/ITitrBd.ttf
    - family: titr1
      fonts:
        - asset: fonts/BTitrBd.ttf
    - family: Vazir
      fonts:
        - asset: fonts/VazirBold.ttf